testa_velha.cpp File Reference
#include `lib/catch.hpp`
#include `jogo/velha.hpp`
Macros
#define CATCH_CONFIG_MAIN
Functions
TEST_CASE (`Jogo indefinido com apenas um X`, `[indefinido]`)
TEST_CASE (`Vitória na segunda linha para o jogador 2`)
TEST_CASE (`Vitória na segunda linha para o jogador 1`)
TEST_CASE (`Vitória na primeira linha para X`)
TEST_CASE (`Vitória na primeira linha para O`)
TEST_CASE (`Vitoria na terceira linha para O`)
TEST_CASE (`Vitoria na terceira linha para X`)
TEST_CASE (`Vitória na primeira coluna para X`)
TEST_CASE (`Vitória na primeira coluna para O`)
TEST_CASE (`Vitória na segunda coluna para X`)
TEST_CASE (`Vitória na segunda coluna para O`)
TEST_CASE (`Vitória na terceira coluna para X`)
TEST_CASE (`Vitória na terceira coluna para O`)
TEST_CASE (`Vitória na diagonal principal para X`)
TEST_CASE (`Vitória na diagonal principal para O`)
TEST_CASE (`Vitória na diagonal secundária para X`)
TEST_CASE (`Vitória na diagonal secundária para O`)
TEST_CASE (`Empate`)
TEST_CASE (`Jogo impossível - TODO O`)
TEST_CASE (`Jogo impossível - TODO X`)
TEST_CASE (`Jogo impossível - número desigual de X e O`)
TEST_CASE (`Jogo impossível - dois vencedores`)
Macro Definition Documentation
CATCH_CONFIG_MAIN
#define CATCH_CONFIG_MAIN
Definition at line 3 of file testa_velha.cpp.
Function Documentation
TEST_CASE() [1/22]
TEST_CASE (`Empate`)
Definition at line 164 of file testa_velha.cpp.
                    {
    int tabuleiro[3][3] = {
        {1, 2, 1},
        {1, 1, 2},
        {2, 1, 2}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 0);
}
References verifica_jogo_da_velha().
TEST_CASE() [2/22]
TEST_CASE (`Jogo impossível - dois vencedores`)
Definition at line 200 of file testa_velha.cpp.
                                                {
    int tabuleiro[3][3] = {
        {1, 1, 1},
        {2, 2, 2},
        {0, 0, 0}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == -2);
}
References verifica_jogo_da_velha().
TEST_CASE() [3/22]
TEST_CASE (`Jogo impossível - número desigual de X e O`)
Definition at line 191 of file testa_velha.cpp.
                                                          {
    int tabuleiro[3][3] = {
        {1, 1, 1},
        {1, 0, 0},
        {0, 0, 2}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == -2);
}
References verifica_jogo_da_velha().
TEST_CASE() [4/22]
TEST_CASE (`Jogo impossível - TODO O`)
Definition at line 173 of file testa_velha.cpp.
                                       {
    int tabuleiro[3][3] = {
        {2, 2, 2},
        {2, 2, 2},
        {2, 2, 2}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == -2);
}
References verifica_jogo_da_velha().
TEST_CASE() [5/22]
TEST_CASE (`Jogo impossível - TODO X`)
Definition at line 182 of file testa_velha.cpp.
                                       {
    int tabuleiro[3][3] = {
        {1, 1, 1},
        {1, 1, 1},
        {1, 1, 1}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == -2);
}
References verifica_jogo_da_velha().
TEST_CASE() [6/22]
TEST_CASE (`Jogo indefinido com apenas um X` , `` [indefinido])
Definition at line 7 of file testa_velha.cpp.
                                                             {
    int tabuleiro[3][3] = {
        {1, 0, 0},
        {0, 0, 0},
        {0, 0, 0}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == -1);
}
References verifica_jogo_da_velha().
TEST_CASE() [7/22]
TEST_CASE (`Vitoria na terceira linha para O`)
Definition at line 56 of file testa_velha.cpp.
                                              {
    int tabuleiro[3][3] = {
        {1, 0, 1},
        {0, 1, 0},
        {2, 2, 2}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 2);
}
References verifica_jogo_da_velha().
TEST_CASE() [8/22]
TEST_CASE (`Vitoria na terceira linha para X`)
Definition at line 65 of file testa_velha.cpp.
                                              {
    int tabuleiro[3][3] = {
        {2, 0, 2},
        {0, 2, 0},
        {1, 1, 1}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 1);
}
References verifica_jogo_da_velha().
TEST_CASE() [9/22]
TEST_CASE (`Vitória na diagonal principal para O`)
Definition at line 137 of file testa_velha.cpp.
                                                   {
    int tabuleiro[3][3] = {
        {2, 0, 1},
        {0, 2, 1},
        {1, 0, 2}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 2);
}
References verifica_jogo_da_velha().
TEST_CASE() [10/22]
TEST_CASE (`Vitória na diagonal principal para X`)
Definition at line 128 of file testa_velha.cpp.
                                                   {
    int tabuleiro[3][3] = {
        {1, 0, 2},
        {0, 1, 0},
        {2, 0, 1}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 1);
}
References verifica_jogo_da_velha().
TEST_CASE() [11/22]
TEST_CASE (`Vitória na diagonal secundária para O`)
Definition at line 155 of file testa_velha.cpp.
                                                     {
    int tabuleiro[3][3] = {
        {0, 0, 2},
        {1, 2, 0},
        {2, 1, 1}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 2);
}
References verifica_jogo_da_velha().
TEST_CASE() [12/22]
TEST_CASE (`Vitória na diagonal secundária para X`)
Definition at line 146 of file testa_velha.cpp.
                                                     {
    int tabuleiro[3][3] = {
        {0, 0, 1},
        {2, 1, 0},
        {1, 2, 2}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 1);
}
References verifica_jogo_da_velha().
TEST_CASE() [13/22]
TEST_CASE (`Vitória na primeira coluna para O`)
Definition at line 83 of file testa_velha.cpp.
                                                {
    int tabuleiro[3][3] = {
        {2, 0, 1},
        {2, 1, 0},
        {2, 0, 1}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 2);
}
References verifica_jogo_da_velha().
TEST_CASE() [14/22]
TEST_CASE (`Vitória na primeira coluna para X`)
Definition at line 74 of file testa_velha.cpp.
                                                {
    int tabuleiro[3][3] = {
        {1, 0, 2},
        {1, 2, 0},
        {1, 0, 2}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 1);
}
References verifica_jogo_da_velha().
TEST_CASE() [15/22]
TEST_CASE (`Vitória na primeira linha para O`)
Definition at line 46 of file testa_velha.cpp.
                                               {
    int tabuleiro[3][3] = {
        {2, 2, 2},
        {1, 0, 1},
        {1, 1, 0}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 2);
}
References verifica_jogo_da_velha().
TEST_CASE() [16/22]
TEST_CASE (`Vitória na primeira linha para X`)
Definition at line 36 of file testa_velha.cpp.
                                               {
    int tabuleiro[3][3] = {
        {1, 1, 1},
        {2, 0, 2},
        {0, 0, 0}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 1);
}
References verifica_jogo_da_velha().
TEST_CASE() [17/22]
TEST_CASE (`Vitória na segunda coluna para O`)
Definition at line 101 of file testa_velha.cpp.
                                               {
    int tabuleiro[3][3] = {
        {1, 2, 1},
        {0, 2, 1},
        {1, 2, 0}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 2);
}
References verifica_jogo_da_velha().
TEST_CASE() [18/22]
TEST_CASE (`Vitória na segunda coluna para X`)
Definition at line 92 of file testa_velha.cpp.
                                               {
    int tabuleiro[3][3] = {
        {0, 1, 2},
        {0, 1, 0},
        {2, 1, 0}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 1);
}
References verifica_jogo_da_velha().
TEST_CASE() [19/22]
TEST_CASE (`Vitória na segunda linha para o jogador 1`)
Definition at line 26 of file testa_velha.cpp.
                                                        {
    int tabuleiro[3][3] = {
        {1, 0, 2},
        {1, 1, 1},
        {2, 0, 2}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 1);
}
References verifica_jogo_da_velha().
TEST_CASE() [20/22]
TEST_CASE (`Vitória na segunda linha para o jogador 2`)
Definition at line 16 of file testa_velha.cpp.
                                                        {
    int tabuleiro[3][3] = {
        {1, 1, 2},
        {2, 2, 2},
        {1, 0, 1}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 2);
}
References verifica_jogo_da_velha().
TEST_CASE() [21/22]
TEST_CASE (`Vitória na terceira coluna para O`)
Definition at line 119 of file testa_velha.cpp.
                                                {
    int tabuleiro[3][3] = {
        {1, 1, 2},
        {0, 1, 2},
        {1, 0, 2}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 2);
}
References verifica_jogo_da_velha().
TEST_CASE() [22/22]
TEST_CASE (`Vitória na terceira coluna para X`)
Definition at line 110 of file testa_velha.cpp.
                                                {
    int tabuleiro[3][3] = {
        {0, 2, 1},
        {0, 0, 1},
        {2, 0, 1}
    };
    REQUIRE(verifica_jogo_da_velha(tabuleiro) == 1);
}
References verifica_jogo_da_velha().